# This query generates the triples that will link the artist with the genres.
# To do so, it uses the name of the tags included as an atribute for the artist
# and link it with the genre of the same name.

PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

construct {
    ?artist dbo:genre ?genre 
}
where {
    ?artist dbo:genre ?tag .
    ?genre a mo:Genre .
    ?genre foaf:name ?genre_name .
    filter(?tag = ?genre_name) .
}