PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>


select ?band ?label ?genre
where {
  ?band dbp:class ?class_type.
  filter(str(?class_type) = "artist")
  ?band dbp:label ?label .
  ?band dbo:genre ?genre .
}