PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX : <http://adrigrillo.github.io/music_kg/genre/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

#select (count(distinct ?db_genre) as ?db)
select distinct ?db_genre ?db_name
where {
    service <http://dbpedia.org/sparql> {
        ?db_genre a dbo:Genre .
        ?db_genre rdfs:label ?db_name_en .
        filter(langMatches(lang(?db_name_en), "en")).
        # Transform the lowercase, the language tag and removes anything between paranthesis
        bind(replace(lcase(str(?db_name_en)),"[\\(.*\\)]","") AS ?db_name)
    }
    filter not exists {
        ?genre a mo:Genre .
   		?genre rdfs:label ?db_name
    }
    filter not exists {
        ?genre a mo:Genre .
   		?genre owl:sameAs ?db_genre
    }
}